-- Personal Private Vault — Flyway baseline migration
-- Generated from docs/database/personal-private-vault-schema-v1-FROZEN-final.dbml (v1.3 frozen logical baseline).
-- Phase 1 policy: structural schema, DBML checks/uniques/indexes/FKs, and selected PostgreSQL-only
-- invariants that are fully specified by the frozen notes. Cross-table business invariants remain
-- owned by their application modules unless/until a later migration can encode them without ambiguity.

CREATE TYPE vault_entry_type AS ENUM ('FICTION', 'FILM', 'PERSON', 'FILM_CREDIT', 'IMAGE', 'ALBUM', 'BRAND', 'LOCATION', 'STUDY', 'INFORMATION', 'VOCABULARY', 'MUSIC', 'SHOPPING', 'SOFTWARE', 'NOTE', 'SAVED_RESOURCE', 'EXTERNAL_ACCOUNT');
CREATE TYPE rating_grade AS ENUM ('D', 'C', 'B', 'A', 'S');
CREATE TYPE gender AS ENUM ('MALE', 'FEMALE');
CREATE TYPE consumption_status AS ENUM ('UNCONSUMED', 'BEING_CONSUMED', 'CONSUMED');
CREATE TYPE progress_status AS ENUM ('ONGOING', 'COMPLETED', 'SUSPENDED');
CREATE TYPE fiction_format AS ENUM ('NOVEL', 'COMIC');
CREATE TYPE film_format AS ENUM ('MOVIE', 'SERIES');
CREATE TYPE film_production_style AS ENUM ('LIVE_ACTION', 'ANIMATION');
CREATE TYPE person_role AS ENUM ('ACTOR', 'SINGER', 'DIRECTOR', 'AUTHOR', 'ARTIST');
CREATE TYPE film_credit_role AS ENUM ('MAIN', 'SUPPORTING', 'CAMEO', 'GUEST', 'VOICE');
CREATE TYPE study_type AS ENUM ('COURSE', 'BOOK', 'GITHUB_REPOSITORY', 'WEBSITE', 'YOUTUBE_CHANNEL');
CREATE TYPE study_status AS ENUM ('PLANNED', 'IN_PROGRESS', 'PAUSED', 'COMPLETED');
CREATE TYPE information_type AS ENUM ('FINANCE', 'TECHNOLOGY', 'HEALTH', 'OTHER');
CREATE TYPE vocabulary_learning_status AS ENUM ('NEW', 'LEARNING', 'REVIEW', 'MASTERED');
CREATE TYPE srs_review_response AS ENUM ('AGAIN', 'HARD', 'GOOD', 'EASY');
CREATE TYPE music_version AS ENUM ('ORIGINAL', 'COVER', 'PARODY', 'MIX');
CREATE TYPE music_credit_role AS ENUM ('SINGER', 'ARTIST');
CREATE TYPE shopping_status AS ENUM ('WISHLIST', 'PURCHASED');
CREATE TYPE software_type AS ENUM ('APPLICATION', 'EXTENSION');
CREATE TYPE dining_service_style AS ENUM ('A_LA_CARTE', 'BUFFET');
CREATE TYPE platform_kind AS ENUM ('SOCIAL', 'MEDIA', 'MARKETPLACE', 'GAME', 'DEVELOPER', 'OPERATING_SYSTEM', 'BROWSER', 'IDE', 'WEB', 'OTHER');
CREATE TYPE external_account_ownership AS ENUM ('OWNED', 'TRACKED');
CREATE TYPE external_account_type AS ENUM ('SOCIAL', 'GAME', 'YOUTUBE_CHANNEL', 'OTHER');
CREATE TYPE follower_status AS ENUM ('CURRENT_FOLLOWER', 'NO_LONGER_FOLLOWING', 'NOT_FOLLOWING', 'UNKNOWN');
CREATE TYPE relationship_source AS ENUM ('MANUAL', 'SNAPSHOT', 'IMPORT', 'API');
CREATE TYPE follow_status AS ENUM ('FOLLOWED', 'NOT_FOLLOWED', 'UNKNOWN');
CREATE TYPE follower_snapshot_source AS ENUM ('MANUAL', 'IMPORT', 'API');
CREATE TYPE feed_source_type AS ENUM ('GITHUB_TRENDING', 'HACKER_NEWS', 'REDDIT', 'RSS', 'WEBSITE');
CREATE TYPE saved_resource_kind AS ENUM ('ARTICLE', 'REPOSITORY', 'SOCIAL_POST', 'WEB_PAGE', 'OTHER');
CREATE TYPE import_format AS ENUM ('CSV', 'JSON', 'MARKDOWN');
CREATE TYPE import_target_type AS ENUM ('STUDY', 'INFORMATION', 'VOCABULARY', 'NOTE');
CREATE TYPE import_job_status AS ENUM ('CREATED', 'PARSED', 'VALIDATED', 'IMPORTED', 'FAILED', 'CANCELLED');
CREATE TYPE import_item_status AS ENUM ('VALID', 'DUPLICATE', 'INVALID', 'IMPORTED', 'UPDATED', 'SKIPPED');
CREATE TYPE wallet_type AS ENUM ('CASH', 'BANK_ACCOUNT', 'CARD', 'E_WALLET', 'OTHER');
CREATE TYPE financial_transaction_type AS ENUM ('INCOME', 'EXPENSE', 'TRANSFER');
CREATE TYPE financial_transaction_status AS ENUM ('PENDING', 'POSTED', 'CANCELLED');
CREATE TYPE transaction_category_kind AS ENUM ('INCOME', 'EXPENSE', 'BOTH');
CREATE TYPE recurring_posting_mode AS ENUM ('AUTO_POST', 'REQUIRE_CONFIRMATION');
CREATE TYPE recurrence_frequency AS ENUM ('DAILY', 'WEEKLY', 'MONTHLY', 'YEARLY');
CREATE TYPE day_of_week AS ENUM ('MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY', 'SUNDAY');
CREATE TYPE billing_cycle AS ENUM ('WEEKLY', 'MONTHLY', 'YEARLY', 'CUSTOM');

CREATE TABLE app_users (
    id smallint PRIMARY KEY DEFAULT 1,
    email varchar(320) NOT NULL UNIQUE,
    username varchar(100) NOT NULL UNIQUE,
    password_hash varchar(255) NOT NULL,
    pin_hash varchar(255) NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT chk_app_users_singleton_id CHECK (id = 1)
);

CREATE TABLE refresh_tokens (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id smallint NOT NULL,
    token_hash varchar(255) NOT NULL UNIQUE,
    expires_at timestamptz NOT NULL,
    revoked_at timestamptz,
    replaced_by_token_id bigint UNIQUE,
    user_agent text,
    ip_address inet,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE app_settings (
    id smallint PRIMARY KEY DEFAULT 1,
    timezone varchar(64) NOT NULL DEFAULT 'Asia/Ho_Chi_Minh',
    default_currency_code varchar(3) NOT NULL,
    pagination_size int NOT NULL DEFAULT 20,
    private_mode_auto_lock_minutes int NOT NULL DEFAULT 5,
    backup_enabled boolean NOT NULL DEFAULT false,
    backup_interval_hours int,
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT chk_app_settings_singleton_id CHECK (id = 1),
    CONSTRAINT chk_app_settings_pagination_size CHECK (pagination_size > 0),
    CONSTRAINT chk_app_settings_auto_lock CHECK (private_mode_auto_lock_minutes > 0),
    CONSTRAINT chk_app_settings_backup_interval CHECK (backup_interval_hours IS NULL OR backup_interval_hours > 0),
    CONSTRAINT chk_app_settings_backup_enabled_interval CHECK (NOT backup_enabled OR backup_interval_hours IS NOT NULL)
);

CREATE TABLE countries (
    code varchar(2) PRIMARY KEY,
    name_en varchar(150) NOT NULL,
    name_vi varchar(150)
);

CREATE TABLE languages (
    code varchar(10) PRIMARY KEY,
    name_en varchar(100) NOT NULL,
    name_vi varchar(100)
);

CREATE TABLE currencies (
    code varchar(3) PRIMARY KEY,
    name varchar(100) NOT NULL,
    symbol varchar(16),
    decimal_places int NOT NULL DEFAULT 2
);

CREATE TABLE platforms (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(100) NOT NULL UNIQUE,
    kind platform_kind NOT NULL,
    url varchar(2048),
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE vault_entries (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entry_type vault_entry_type NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    deleted_at timestamptz
);

CREATE TABLE favorites (
    vault_entry_id bigint PRIMARY KEY,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE ratings (
    vault_entry_id bigint PRIMARY KEY,
    grade rating_grade NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE tags (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(100) NOT NULL UNIQUE,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE vault_entry_tags (
    vault_entry_id bigint NOT NULL,
    tag_id bigint NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT pk_vault_entry_tags PRIMARY KEY (vault_entry_id, tag_id)
);

CREATE TABLE persons (
    id bigint PRIMARY KEY,
    name varchar(255) NOT NULL,
    avatar_url varchar(2048),
    gender gender,
    birth_date date,
    height_cm numeric(6,2),
    weight_kg numeric(6,2),
    nationality_code varchar(2),
    notes text,
    CONSTRAINT chk_person_height CHECK (height_cm IS NULL OR height_cm > 0),
    CONSTRAINT chk_person_weight CHECK (weight_kg IS NULL OR weight_kg > 0)
);

CREATE TABLE person_roles (
    person_id bigint NOT NULL,
    role person_role NOT NULL,
    CONSTRAINT pk_person_roles PRIMARY KEY (person_id, role)
);

CREATE TABLE creator_groups (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(255) NOT NULL UNIQUE,
    description text,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE creator_group_members (
    creator_group_id bigint NOT NULL,
    person_id bigint NOT NULL,
    CONSTRAINT pk_creator_group_members PRIMARY KEY (creator_group_id, person_id)
);

CREATE TABLE fiction_genres (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(150) NOT NULL UNIQUE,
    description text
);

CREATE TABLE film_genres (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(150) NOT NULL UNIQUE,
    description text
);

CREATE TABLE story_archetypes (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(150) NOT NULL UNIQUE,
    description text
);

CREATE TABLE world_settings (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(150) NOT NULL UNIQUE,
    description text
);

CREATE TABLE fictions (
    id bigint PRIMARY KEY,
    title varchar(500) NOT NULL,
    original_title varchar(500),
    nationality_code varchar(2),
    poster_url varchar(2048),
    format fiction_format NOT NULL,
    is_nsfw boolean NOT NULL DEFAULT false,
    genre_id bigint NOT NULL,
    author_person_id bigint,
    author_group_id bigint,
    description text,
    total_chapters int,
    progress_status progress_status NOT NULL DEFAULT 'ONGOING',
    consumption_status consumption_status NOT NULL DEFAULT 'UNCONSUMED',
    current_progress_text varchar(255),
    review text,
    CONSTRAINT chk_fiction_total_chapters CHECK (total_chapters IS NULL OR total_chapters >= 0),
    CONSTRAINT chk_fiction_author_source CHECK (((author_person_id IS NOT NULL AND author_group_id IS NULL) OR (author_person_id IS NULL AND author_group_id IS NOT NULL)))
);

CREATE TABLE fiction_story_archetypes (
    fiction_id bigint NOT NULL,
    story_archetype_id bigint NOT NULL,
    CONSTRAINT pk_fiction_story_archetypes PRIMARY KEY (fiction_id, story_archetype_id)
);

CREATE TABLE fiction_world_settings (
    fiction_id bigint NOT NULL,
    world_setting_id bigint NOT NULL,
    CONSTRAINT pk_fiction_world_settings PRIMARY KEY (fiction_id, world_setting_id)
);

CREATE TABLE fiction_links (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fiction_id bigint NOT NULL,
    language_code varchar(10),
    link_type varchar(50) NOT NULL,
    label varchar(255),
    url varchar(2048) NOT NULL,
    is_primary boolean NOT NULL DEFAULT false,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE films (
    id bigint PRIMARY KEY,
    title varchar(500) NOT NULL,
    original_title varchar(500),
    nationality_code varchar(2),
    poster_url varchar(2048),
    format film_format NOT NULL,
    production_style film_production_style NOT NULL,
    is_nsfw boolean NOT NULL DEFAULT false,
    director_person_id bigint,
    description text,
    total_episodes int,
    progress_status progress_status NOT NULL DEFAULT 'ONGOING',
    consumption_status consumption_status NOT NULL DEFAULT 'UNCONSUMED',
    current_progress_text varchar(255),
    review text,
    CONSTRAINT chk_film_total_episodes CHECK (total_episodes IS NULL OR total_episodes >= 0)
);

CREATE TABLE film_genre_assignments (
    film_id bigint NOT NULL,
    genre_id bigint NOT NULL,
    CONSTRAINT pk_film_genre_assignments PRIMARY KEY (film_id, genre_id)
);

CREATE TABLE film_story_archetypes (
    film_id bigint NOT NULL,
    story_archetype_id bigint NOT NULL,
    CONSTRAINT pk_film_story_archetypes PRIMARY KEY (film_id, story_archetype_id)
);

CREATE TABLE film_world_settings (
    film_id bigint NOT NULL,
    world_setting_id bigint NOT NULL,
    CONSTRAINT pk_film_world_settings PRIMARY KEY (film_id, world_setting_id)
);

CREATE TABLE film_links (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    film_id bigint NOT NULL,
    language_code varchar(10),
    label varchar(255),
    url varchar(2048) NOT NULL,
    is_primary boolean NOT NULL DEFAULT false,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE film_credits (
    id bigint PRIMARY KEY,
    film_id bigint NOT NULL,
    person_id bigint NOT NULL,
    role film_credit_role NOT NULL,
    character_name varchar(255),
    note text
);

CREATE TABLE albums (
    id bigint PRIMARY KEY,
    title varchar(500) NOT NULL,
    description text
);

CREATE TABLE images (
    id bigint PRIMARY KEY,
    album_id bigint,
    title varchar(500),
    image_type varchar(100),
    object_key varchar(1024) NOT NULL UNIQUE,
    source_url varchar(2048),
    mime_type varchar(100),
    size_bytes bigint,
    width_px int,
    height_px int,
    checksum_sha256 varchar(64) UNIQUE,
    captured_at timestamptz,
    location_text varchar(500),
    CONSTRAINT chk_image_size CHECK (size_bytes IS NULL OR size_bytes >= 0),
    CONSTRAINT chk_image_width CHECK (width_px IS NULL OR width_px > 0),
    CONSTRAINT chk_image_height CHECK (height_px IS NULL OR height_px > 0)
);

CREATE TABLE brands (
    id bigint PRIMARY KEY,
    name varchar(255) NOT NULL,
    logo_url varchar(2048),
    nationality_code varchar(2),
    description text,
    min_price numeric(19,4),
    max_price numeric(19,4),
    currency_code varchar(3),
    review text,
    CONSTRAINT chk_brands_min_price CHECK (min_price IS NULL OR min_price >= 0),
    CONSTRAINT chk_brands_max_price CHECK (max_price IS NULL OR max_price >= 0),
    CONSTRAINT chk_brands_price_range CHECK (min_price IS NULL OR max_price IS NULL OR min_price <= max_price),
    CONSTRAINT chk_brands_price_currency CHECK (currency_code IS NOT NULL OR (min_price IS NULL AND max_price IS NULL))
);

CREATE TABLE location_categories (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(150) NOT NULL UNIQUE,
    description text
);

CREATE TABLE addresses (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    label varchar(255),
    address_type varchar(100),
    country_code varchar(2) NOT NULL,
    administrative_area varchar(255),
    locality varchar(255),
    sublocality varchar(255),
    street_address varchar(500),
    postal_code varchar(32),
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE locations (
    id bigint PRIMARY KEY,
    brand_id bigint,
    address_id bigint NOT NULL,
    name varchar(500) NOT NULL,
    image_url varchar(2048),
    description text,
    phone varchar(64),
    website_url varchar(2048),
    business_hours_known boolean NOT NULL DEFAULT false,
    min_price numeric(19,4),
    max_price numeric(19,4),
    currency_code varchar(3),
    review text,
    CONSTRAINT chk_locations_min_price CHECK (min_price IS NULL OR min_price >= 0),
    CONSTRAINT chk_locations_max_price CHECK (max_price IS NULL OR max_price >= 0),
    CONSTRAINT chk_locations_price_range CHECK (min_price IS NULL OR max_price IS NULL OR min_price <= max_price),
    CONSTRAINT chk_locations_price_currency CHECK (currency_code IS NOT NULL OR (min_price IS NULL AND max_price IS NULL))
);

CREATE TABLE location_category_assignments (
    location_id bigint NOT NULL,
    category_id bigint NOT NULL,
    CONSTRAINT pk_location_category_assignments PRIMARY KEY (location_id, category_id)
);

CREATE TABLE location_dining_service_styles (
    location_id bigint NOT NULL,
    service_style dining_service_style NOT NULL,
    CONSTRAINT pk_location_dining_service_styles PRIMARY KEY (location_id, service_style)
);

CREATE TABLE location_business_hours (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    location_id bigint NOT NULL,
    day_of_week day_of_week NOT NULL,
    sequence int NOT NULL DEFAULT 1,
    open_time time NOT NULL,
    close_time time NOT NULL,
    CONSTRAINT chk_location_business_hours_sequence CHECK (sequence > 0)
);

CREATE TABLE study_items (
    id bigint PRIMARY KEY,
    title varchar(500) NOT NULL,
    poster_url varchar(2048),
    type study_type NOT NULL,
    site_domain varchar(255),
    youtube_channel_account_id bigint UNIQUE,
    author_person_id bigint,
    author_group_id bigint,
    published_date date,
    price_amount numeric(19,4),
    currency_code varchar(3),
    description text,
    url varchar(2048),
    review text,
    learning_status study_status NOT NULL DEFAULT 'PLANNED',
    progress_percent numeric(5,2),
    current_progress_text varchar(500),
    CONSTRAINT chk_study_progress_percent CHECK (progress_percent IS NULL OR (progress_percent >= 0 AND progress_percent <= 100)),
    CONSTRAINT chk_study_author_source CHECK (NOT (author_person_id IS NOT NULL AND author_group_id IS NOT NULL)),
    CONSTRAINT chk_study_price CHECK (price_amount IS NULL OR price_amount >= 0),
    CONSTRAINT chk_study_currency CHECK (currency_code IS NOT NULL OR price_amount IS NULL),
    CONSTRAINT chk_study_website_fields CHECK ((type = 'WEBSITE' AND site_domain IS NOT NULL AND url IS NOT NULL) OR (type <> 'WEBSITE' AND site_domain IS NULL)),
    CONSTRAINT chk_study_youtube_fields CHECK ((type = 'YOUTUBE_CHANNEL' AND youtube_channel_account_id IS NOT NULL) OR (type <> 'YOUTUBE_CHANNEL' AND youtube_channel_account_id IS NULL))
);

CREATE TABLE information_items (
    id bigint PRIMARY KEY,
    title varchar(500) NOT NULL,
    type information_type NOT NULL,
    description text,
    content_markdown text,
    example text,
    source_name varchar(500),
    source_url varchar(2048)
);

CREATE TABLE vocabulary_items (
    id bigint PRIMARY KEY,
    word varchar(500) NOT NULL,
    language_code varchar(10) NOT NULL,
    meaning text NOT NULL,
    example text,
    pronunciation varchar(500),
    ipa varchar(255),
    part_of_speech varchar(100),
    source_name varchar(500),
    source_url varchar(2048),
    learning_status vocabulary_learning_status NOT NULL DEFAULT 'NEW',
    next_review_at timestamptz,
    interval_days int NOT NULL DEFAULT 0,
    ease_factor numeric(5,2) NOT NULL DEFAULT 2.50,
    repetition_count int NOT NULL DEFAULT 0,
    lapse_count int NOT NULL DEFAULT 0,
    CONSTRAINT chk_vocabulary_interval_days CHECK (interval_days >= 0),
    CONSTRAINT chk_vocabulary_ease_factor CHECK (ease_factor > 0),
    CONSTRAINT chk_vocabulary_repetition_count CHECK (repetition_count >= 0),
    CONSTRAINT chk_vocabulary_lapse_count CHECK (lapse_count >= 0)
);

CREATE TABLE vocabulary_reviews (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vocabulary_id bigint NOT NULL,
    response srs_review_response NOT NULL,
    reviewed_at timestamptz NOT NULL DEFAULT now(),
    previous_interval_days int,
    new_interval_days int,
    previous_ease_factor numeric(5,2),
    new_ease_factor numeric(5,2),
    next_review_at timestamptz,
    CONSTRAINT chk_vocab_review_previous_interval CHECK (previous_interval_days IS NULL OR previous_interval_days >= 0),
    CONSTRAINT chk_vocab_review_new_interval CHECK (new_interval_days IS NULL OR new_interval_days >= 0),
    CONSTRAINT chk_vocab_review_previous_ease CHECK (previous_ease_factor IS NULL OR previous_ease_factor > 0),
    CONSTRAINT chk_vocab_review_new_ease CHECK (new_ease_factor IS NULL OR new_ease_factor > 0)
);

CREATE TABLE notes (
    id bigint PRIMARY KEY,
    title varchar(500) NOT NULL,
    content_markdown text NOT NULL,
    summary text,
    source_name varchar(500),
    source_url varchar(2048),
    imported_file_name varchar(500),
    imported_file_hash varchar(64) UNIQUE,
    frontmatter jsonb
);

CREATE TABLE music_tracks (
    id bigint PRIMARY KEY,
    title varchar(500) NOT NULL,
    version music_version NOT NULL DEFAULT 'ORIGINAL',
    platform_id bigint,
    url varchar(2048)
);

CREATE TABLE music_track_people (
    music_id bigint NOT NULL,
    person_id bigint NOT NULL,
    role music_credit_role NOT NULL,
    CONSTRAINT pk_music_track_people PRIMARY KEY (music_id, person_id, role)
);

CREATE TABLE shopping_items (
    id bigint PRIMARY KEY,
    name varchar(500) NOT NULL,
    avatar_url varchar(2048),
    description text,
    price_amount numeric(19,4),
    currency_code varchar(3),
    platform_id bigint,
    status shopping_status NOT NULL DEFAULT 'WISHLIST',
    url varchar(2048),
    purchased_at timestamptz,
    CONSTRAINT chk_shopping_price CHECK (price_amount IS NULL OR price_amount >= 0),
    CONSTRAINT chk_shopping_currency CHECK (currency_code IS NOT NULL OR price_amount IS NULL),
    CONSTRAINT chk_shopping_purchased_at CHECK (status = 'PURCHASED' OR purchased_at IS NULL)
);

CREATE TABLE software_items (
    id bigint PRIMARY KEY,
    name varchar(500) NOT NULL,
    type software_type NOT NULL,
    logo_url varchar(2048),
    description text,
    price_amount numeric(19,4),
    currency_code varchar(3),
    url varchar(2048),
    review text,
    CONSTRAINT chk_software_price CHECK (price_amount IS NULL OR price_amount >= 0),
    CONSTRAINT chk_software_currency CHECK (currency_code IS NOT NULL OR price_amount IS NULL)
);

CREATE TABLE software_item_platforms (
    software_id bigint NOT NULL,
    platform_id bigint NOT NULL,
    CONSTRAINT pk_software_item_platforms PRIMARY KEY (software_id, platform_id)
);

CREATE TABLE external_accounts (
    id bigint PRIMARY KEY,
    platform_id bigint NOT NULL,
    ownership external_account_ownership NOT NULL,
    account_type external_account_type NOT NULL,
    username varchar(255),
    external_id varchar(255),
    display_name varchar(500),
    avatar_url varchar(2048),
    banner_url varchar(2048),
    profile_description text,
    owner_name varchar(500),
    url varchar(2048),
    notes text,
    CONSTRAINT chk_external_account_identifier CHECK (username IS NOT NULL OR external_id IS NOT NULL OR url IS NOT NULL)
);

CREATE TABLE external_account_relationships (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_account_id bigint NOT NULL,
    target_account_id bigint NOT NULL,
    follower_status follower_status,
    source relationship_source NOT NULL DEFAULT 'MANUAL',
    follow_status follow_status NOT NULL DEFAULT 'UNKNOWN',
    has_liked_post boolean NOT NULL DEFAULT false,
    note text,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT chk_external_relationship_not_self CHECK (owner_account_id <> target_account_id)
);

CREATE TABLE follower_snapshots (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_account_id bigint NOT NULL,
    captured_at timestamptz NOT NULL,
    source follower_snapshot_source NOT NULL,
    reported_total_count int,
    imported_file_name varchar(500),
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE follower_snapshot_entries (
    snapshot_id bigint NOT NULL,
    target_account_id bigint NOT NULL,
    username_snapshot varchar(255),
    display_name_snapshot varchar(500),
    external_id_snapshot varchar(255),
    profile_url_snapshot varchar(2048),
    CONSTRAINT pk_follower_snapshot_entries PRIMARY KEY (snapshot_id, target_account_id)
);

CREATE TABLE feed_sources (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(255) NOT NULL,
    type feed_source_type NOT NULL,
    source_url varchar(2048),
    feed_url varchar(2048),
    enabled boolean NOT NULL DEFAULT true,
    scheduled_refresh_enabled boolean NOT NULL DEFAULT false,
    refresh_interval_minutes int,
    config jsonb,
    last_fetched_at timestamptz,
    next_fetch_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT chk_feed_refresh_interval CHECK (refresh_interval_minutes IS NULL OR refresh_interval_minutes > 0),
    CONSTRAINT chk_feed_scheduled_interval CHECK (NOT scheduled_refresh_enabled OR refresh_interval_minutes IS NOT NULL)
);

CREATE TABLE feed_items (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    feed_source_id bigint NOT NULL,
    external_id varchar(500),
    title varchar(1000) NOT NULL,
    url varchar(2048) NOT NULL,
    url_hash varchar(64) NOT NULL,
    author varchar(500),
    summary text,
    published_at timestamptz,
    fetched_at timestamptz NOT NULL DEFAULT now(),
    raw_metadata jsonb
);

CREATE TABLE saved_resources (
    id bigint PRIMARY KEY,
    feed_item_id bigint,
    kind saved_resource_kind NOT NULL,
    source_name varchar(500),
    source_url varchar(2048),
    external_id varchar(500),
    title varchar(1000) NOT NULL,
    resource_url varchar(2048) NOT NULL,
    resource_url_hash varchar(64) NOT NULL UNIQUE,
    author varchar(500),
    summary text,
    published_at timestamptz,
    fetched_at timestamptz,
    saved_at timestamptz NOT NULL DEFAULT now(),
    raw_metadata jsonb
);

CREATE TABLE saved_resource_conversions (
    saved_resource_id bigint NOT NULL,
    target_vault_entry_id bigint NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT pk_saved_resource_conversions PRIMARY KEY (saved_resource_id, target_vault_entry_id)
);

CREATE TABLE import_jobs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    target_type import_target_type NOT NULL,
    format import_format NOT NULL,
    original_file_name varchar(500) NOT NULL,
    file_hash varchar(64),
    raw_file_object_key varchar(1024),
    status import_job_status NOT NULL DEFAULT 'CREATED',
    total_items int NOT NULL DEFAULT 0,
    valid_items int NOT NULL DEFAULT 0,
    duplicate_items int NOT NULL DEFAULT 0,
    invalid_items int NOT NULL DEFAULT 0,
    imported_items int NOT NULL DEFAULT 0,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT chk_import_total_items CHECK (total_items >= 0),
    CONSTRAINT chk_import_valid_items CHECK (valid_items >= 0),
    CONSTRAINT chk_import_duplicate_items CHECK (duplicate_items >= 0),
    CONSTRAINT chk_import_invalid_items CHECK (invalid_items >= 0),
    CONSTRAINT chk_import_imported_items CHECK (imported_items >= 0),
    CONSTRAINT chk_import_counts_within_total CHECK (valid_items <= total_items AND duplicate_items <= total_items AND invalid_items <= total_items AND imported_items <= total_items),
    CONSTRAINT chk_import_classified_counts_total CHECK (valid_items + duplicate_items + invalid_items <= total_items)
);

CREATE TABLE import_job_items (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    import_job_id bigint NOT NULL,
    item_index int NOT NULL,
    parsed_payload jsonb,
    status import_item_status NOT NULL,
    duplicate_vault_entry_id bigint,
    error_message text,
    imported_vault_entry_id bigint
);

CREATE TABLE wallets (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(255) NOT NULL,
    type wallet_type NOT NULL,
    currency_code varchar(3) NOT NULL,
    opening_balance numeric(19,4) NOT NULL DEFAULT 0,
    notes text,
    active boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    deleted_at timestamptz
);

CREATE TABLE transaction_categories (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(255) NOT NULL,
    kind transaction_category_kind NOT NULL,
    parent_category_id bigint,
    active boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE financial_transactions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type financial_transaction_type NOT NULL,
    status financial_transaction_status NOT NULL DEFAULT 'POSTED',
    category_id bigint,
    generated_by_recurring_rule_id bigint,
    description varchar(1000),
    notes text,
    occurred_at timestamptz NOT NULL,
    exchange_rate numeric(24,10),
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    deleted_at timestamptz,
    CONSTRAINT chk_financial_transaction_exchange_rate CHECK (exchange_rate IS NULL OR exchange_rate > 0)
);

CREATE TABLE financial_transaction_entries (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_id bigint NOT NULL,
    wallet_id bigint NOT NULL,
    amount_delta numeric(19,4) NOT NULL,
    CONSTRAINT chk_financial_entry_amount_nonzero CHECK (amount_delta <> 0)
);

CREATE TABLE recurring_transaction_rules (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(500) NOT NULL,
    transaction_type financial_transaction_type NOT NULL,
    category_id bigint,
    posting_mode recurring_posting_mode NOT NULL,
    frequency recurrence_frequency NOT NULL,
    interval_count int NOT NULL DEFAULT 1,
    day_of_month int,
    month_of_year int,
    start_date date NOT NULL,
    end_date date,
    posting_time time,
    next_run_at timestamptz,
    description varchar(1000),
    notes text,
    active boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    deleted_at timestamptz,
    CONSTRAINT chk_recurring_interval_count CHECK (interval_count > 0),
    CONSTRAINT chk_recurring_day_of_month CHECK (day_of_month IS NULL OR (day_of_month >= 1 AND day_of_month <= 31)),
    CONSTRAINT chk_recurring_month_of_year CHECK (month_of_year IS NULL OR (month_of_year >= 1 AND month_of_year <= 12)),
    CONSTRAINT chk_recurring_date_range CHECK (end_date IS NULL OR end_date >= start_date)
);

CREATE TABLE recurring_rule_weekdays (
    recurring_rule_id bigint NOT NULL,
    weekday day_of_week NOT NULL,
    CONSTRAINT pk_recurring_rule_weekdays PRIMARY KEY (recurring_rule_id, weekday)
);

CREATE TABLE recurring_rule_entries (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recurring_rule_id bigint NOT NULL,
    wallet_id bigint NOT NULL,
    amount_delta numeric(19,4) NOT NULL,
    CONSTRAINT chk_recurring_entry_amount_nonzero CHECK (amount_delta <> 0)
);

CREATE TABLE subscriptions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(500) NOT NULL,
    provider varchar(500),
    price_amount numeric(19,4) NOT NULL,
    currency_code varchar(3) NOT NULL,
    billing_cycle billing_cycle NOT NULL,
    billing_interval int NOT NULL DEFAULT 1,
    custom_cycle_days int,
    next_billing_date date,
    auto_renew boolean NOT NULL DEFAULT true,
    payment_wallet_id bigint,
    recurring_rule_id bigint UNIQUE,
    url varchar(2048),
    notes text,
    active boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    deleted_at timestamptz,
    CONSTRAINT chk_subscription_price CHECK (price_amount >= 0),
    CONSTRAINT chk_subscription_billing_interval CHECK (billing_interval > 0),
    CONSTRAINT chk_subscription_custom_cycle CHECK ((billing_cycle = 'CUSTOM' AND custom_cycle_days IS NOT NULL AND custom_cycle_days > 0) OR (billing_cycle <> 'CUSTOM' AND custom_cycle_days IS NULL))
);

CREATE TABLE diary_entries (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entry_date date NOT NULL,
    title varchar(500),
    content_markdown text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    deleted_at timestamptz
);

CREATE TABLE personal_profiles (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(255) NOT NULL,
    relationship varchar(100) NOT NULL,
    is_self boolean NOT NULL DEFAULT false,
    gender gender,
    birth_date date,
    nationality_code varchar(2),
    phone varchar(64),
    email varchar(320),
    address_id bigint,
    occupation varchar(255),
    notes_markdown text,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    deleted_at timestamptz
);

ALTER TABLE refresh_tokens ADD CONSTRAINT fk_refresh_tokens_user_id_app_users FOREIGN KEY (user_id) REFERENCES app_users (id);
ALTER TABLE refresh_tokens ADD CONSTRAINT fk_refresh_tokens_replaced_by_token_id_refresh_tokens FOREIGN KEY (replaced_by_token_id) REFERENCES refresh_tokens (id);
ALTER TABLE app_settings ADD CONSTRAINT fk_app_settings_default_currency_code_currencies FOREIGN KEY (default_currency_code) REFERENCES currencies (code);
ALTER TABLE favorites ADD CONSTRAINT fk_favorites_vault_entry_id_vault_entries FOREIGN KEY (vault_entry_id) REFERENCES vault_entries (id);
ALTER TABLE ratings ADD CONSTRAINT fk_ratings_vault_entry_id_vault_entries FOREIGN KEY (vault_entry_id) REFERENCES vault_entries (id);
ALTER TABLE vault_entry_tags ADD CONSTRAINT fk_vault_entry_tags_vault_entry_id_vault_entries FOREIGN KEY (vault_entry_id) REFERENCES vault_entries (id);
ALTER TABLE vault_entry_tags ADD CONSTRAINT fk_vault_entry_tags_tag_id_tags FOREIGN KEY (tag_id) REFERENCES tags (id);
ALTER TABLE persons ADD CONSTRAINT fk_persons_id_vault_entries FOREIGN KEY (id) REFERENCES vault_entries (id);
ALTER TABLE persons ADD CONSTRAINT fk_persons_nationality_code_countries FOREIGN KEY (nationality_code) REFERENCES countries (code);
ALTER TABLE person_roles ADD CONSTRAINT fk_person_roles_person_id_persons FOREIGN KEY (person_id) REFERENCES persons (id);
ALTER TABLE creator_group_members ADD CONSTRAINT fk_creator_group_members_creator_group_id_creator_groups FOREIGN KEY (creator_group_id) REFERENCES creator_groups (id);
ALTER TABLE creator_group_members ADD CONSTRAINT fk_creator_group_members_person_id_persons FOREIGN KEY (person_id) REFERENCES persons (id);
ALTER TABLE fictions ADD CONSTRAINT fk_fictions_id_vault_entries FOREIGN KEY (id) REFERENCES vault_entries (id);
ALTER TABLE fictions ADD CONSTRAINT fk_fictions_nationality_code_countries FOREIGN KEY (nationality_code) REFERENCES countries (code);
ALTER TABLE fictions ADD CONSTRAINT fk_fictions_genre_id_fiction_genres FOREIGN KEY (genre_id) REFERENCES fiction_genres (id);
ALTER TABLE fictions ADD CONSTRAINT fk_fictions_author_person_id_persons FOREIGN KEY (author_person_id) REFERENCES persons (id);
ALTER TABLE fictions ADD CONSTRAINT fk_fictions_author_group_id_creator_groups FOREIGN KEY (author_group_id) REFERENCES creator_groups (id);
ALTER TABLE fiction_story_archetypes ADD CONSTRAINT fk_fiction_story_archetypes_fiction_id_fictions FOREIGN KEY (fiction_id) REFERENCES fictions (id);
ALTER TABLE fiction_story_archetypes ADD CONSTRAINT fk_fiction_story_archetypes_story_archetype_id_story_archetypes FOREIGN KEY (story_archetype_id) REFERENCES story_archetypes (id);
ALTER TABLE fiction_world_settings ADD CONSTRAINT fk_fiction_world_settings_fiction_id_fictions FOREIGN KEY (fiction_id) REFERENCES fictions (id);
ALTER TABLE fiction_world_settings ADD CONSTRAINT fk_fiction_world_settings_world_setting_id_world_settings FOREIGN KEY (world_setting_id) REFERENCES world_settings (id);
ALTER TABLE fiction_links ADD CONSTRAINT fk_fiction_links_fiction_id_fictions FOREIGN KEY (fiction_id) REFERENCES fictions (id);
ALTER TABLE fiction_links ADD CONSTRAINT fk_fiction_links_language_code_languages FOREIGN KEY (language_code) REFERENCES languages (code);
ALTER TABLE films ADD CONSTRAINT fk_films_id_vault_entries FOREIGN KEY (id) REFERENCES vault_entries (id);
ALTER TABLE films ADD CONSTRAINT fk_films_nationality_code_countries FOREIGN KEY (nationality_code) REFERENCES countries (code);
ALTER TABLE films ADD CONSTRAINT fk_films_director_person_id_persons FOREIGN KEY (director_person_id) REFERENCES persons (id);
ALTER TABLE film_genre_assignments ADD CONSTRAINT fk_film_genre_assignments_film_id_films FOREIGN KEY (film_id) REFERENCES films (id);
ALTER TABLE film_genre_assignments ADD CONSTRAINT fk_film_genre_assignments_genre_id_film_genres FOREIGN KEY (genre_id) REFERENCES film_genres (id);
ALTER TABLE film_story_archetypes ADD CONSTRAINT fk_film_story_archetypes_film_id_films FOREIGN KEY (film_id) REFERENCES films (id);
ALTER TABLE film_story_archetypes ADD CONSTRAINT fk_film_story_archetypes_story_archetype_id_story_archetypes FOREIGN KEY (story_archetype_id) REFERENCES story_archetypes (id);
ALTER TABLE film_world_settings ADD CONSTRAINT fk_film_world_settings_film_id_films FOREIGN KEY (film_id) REFERENCES films (id);
ALTER TABLE film_world_settings ADD CONSTRAINT fk_film_world_settings_world_setting_id_world_settings FOREIGN KEY (world_setting_id) REFERENCES world_settings (id);
ALTER TABLE film_links ADD CONSTRAINT fk_film_links_film_id_films FOREIGN KEY (film_id) REFERENCES films (id);
ALTER TABLE film_links ADD CONSTRAINT fk_film_links_language_code_languages FOREIGN KEY (language_code) REFERENCES languages (code);
ALTER TABLE film_credits ADD CONSTRAINT fk_film_credits_id_vault_entries FOREIGN KEY (id) REFERENCES vault_entries (id);
ALTER TABLE film_credits ADD CONSTRAINT fk_film_credits_film_id_films FOREIGN KEY (film_id) REFERENCES films (id);
ALTER TABLE film_credits ADD CONSTRAINT fk_film_credits_person_id_persons FOREIGN KEY (person_id) REFERENCES persons (id);
ALTER TABLE albums ADD CONSTRAINT fk_albums_id_vault_entries FOREIGN KEY (id) REFERENCES vault_entries (id);
ALTER TABLE images ADD CONSTRAINT fk_images_id_vault_entries FOREIGN KEY (id) REFERENCES vault_entries (id);
ALTER TABLE images ADD CONSTRAINT fk_images_album_id_albums FOREIGN KEY (album_id) REFERENCES albums (id);
ALTER TABLE brands ADD CONSTRAINT fk_brands_id_vault_entries FOREIGN KEY (id) REFERENCES vault_entries (id);
ALTER TABLE brands ADD CONSTRAINT fk_brands_nationality_code_countries FOREIGN KEY (nationality_code) REFERENCES countries (code);
ALTER TABLE brands ADD CONSTRAINT fk_brands_currency_code_currencies FOREIGN KEY (currency_code) REFERENCES currencies (code);
ALTER TABLE addresses ADD CONSTRAINT fk_addresses_country_code_countries FOREIGN KEY (country_code) REFERENCES countries (code);
ALTER TABLE locations ADD CONSTRAINT fk_locations_id_vault_entries FOREIGN KEY (id) REFERENCES vault_entries (id);
ALTER TABLE locations ADD CONSTRAINT fk_locations_brand_id_brands FOREIGN KEY (brand_id) REFERENCES brands (id);
ALTER TABLE locations ADD CONSTRAINT fk_locations_address_id_addresses FOREIGN KEY (address_id) REFERENCES addresses (id);
ALTER TABLE locations ADD CONSTRAINT fk_locations_currency_code_currencies FOREIGN KEY (currency_code) REFERENCES currencies (code);
ALTER TABLE location_category_assignments ADD CONSTRAINT fk_location_category_assignments_location_id_locations FOREIGN KEY (location_id) REFERENCES locations (id);
ALTER TABLE location_category_assignments ADD CONSTRAINT fk_location_category_assignments_category_id_location__1f3a0624 FOREIGN KEY (category_id) REFERENCES location_categories (id);
ALTER TABLE location_dining_service_styles ADD CONSTRAINT fk_location_dining_service_styles_location_id_locations FOREIGN KEY (location_id) REFERENCES locations (id);
ALTER TABLE location_business_hours ADD CONSTRAINT fk_location_business_hours_location_id_locations FOREIGN KEY (location_id) REFERENCES locations (id);
ALTER TABLE study_items ADD CONSTRAINT fk_study_items_id_vault_entries FOREIGN KEY (id) REFERENCES vault_entries (id);
ALTER TABLE study_items ADD CONSTRAINT fk_study_items_youtube_channel_account_id_external_accounts FOREIGN KEY (youtube_channel_account_id) REFERENCES external_accounts (id);
ALTER TABLE study_items ADD CONSTRAINT fk_study_items_author_person_id_persons FOREIGN KEY (author_person_id) REFERENCES persons (id);
ALTER TABLE study_items ADD CONSTRAINT fk_study_items_author_group_id_creator_groups FOREIGN KEY (author_group_id) REFERENCES creator_groups (id);
ALTER TABLE study_items ADD CONSTRAINT fk_study_items_currency_code_currencies FOREIGN KEY (currency_code) REFERENCES currencies (code);
ALTER TABLE information_items ADD CONSTRAINT fk_information_items_id_vault_entries FOREIGN KEY (id) REFERENCES vault_entries (id);
ALTER TABLE vocabulary_items ADD CONSTRAINT fk_vocabulary_items_id_vault_entries FOREIGN KEY (id) REFERENCES vault_entries (id);
ALTER TABLE vocabulary_items ADD CONSTRAINT fk_vocabulary_items_language_code_languages FOREIGN KEY (language_code) REFERENCES languages (code);
ALTER TABLE vocabulary_reviews ADD CONSTRAINT fk_vocabulary_reviews_vocabulary_id_vocabulary_items FOREIGN KEY (vocabulary_id) REFERENCES vocabulary_items (id);
ALTER TABLE notes ADD CONSTRAINT fk_notes_id_vault_entries FOREIGN KEY (id) REFERENCES vault_entries (id);
ALTER TABLE music_tracks ADD CONSTRAINT fk_music_tracks_id_vault_entries FOREIGN KEY (id) REFERENCES vault_entries (id);
ALTER TABLE music_tracks ADD CONSTRAINT fk_music_tracks_platform_id_platforms FOREIGN KEY (platform_id) REFERENCES platforms (id);
ALTER TABLE music_track_people ADD CONSTRAINT fk_music_track_people_music_id_music_tracks FOREIGN KEY (music_id) REFERENCES music_tracks (id);
ALTER TABLE music_track_people ADD CONSTRAINT fk_music_track_people_person_id_persons FOREIGN KEY (person_id) REFERENCES persons (id);
ALTER TABLE shopping_items ADD CONSTRAINT fk_shopping_items_id_vault_entries FOREIGN KEY (id) REFERENCES vault_entries (id);
ALTER TABLE shopping_items ADD CONSTRAINT fk_shopping_items_currency_code_currencies FOREIGN KEY (currency_code) REFERENCES currencies (code);
ALTER TABLE shopping_items ADD CONSTRAINT fk_shopping_items_platform_id_platforms FOREIGN KEY (platform_id) REFERENCES platforms (id);
ALTER TABLE software_items ADD CONSTRAINT fk_software_items_id_vault_entries FOREIGN KEY (id) REFERENCES vault_entries (id);
ALTER TABLE software_items ADD CONSTRAINT fk_software_items_currency_code_currencies FOREIGN KEY (currency_code) REFERENCES currencies (code);
ALTER TABLE software_item_platforms ADD CONSTRAINT fk_software_item_platforms_software_id_software_items FOREIGN KEY (software_id) REFERENCES software_items (id);
ALTER TABLE software_item_platforms ADD CONSTRAINT fk_software_item_platforms_platform_id_platforms FOREIGN KEY (platform_id) REFERENCES platforms (id);
ALTER TABLE external_accounts ADD CONSTRAINT fk_external_accounts_id_vault_entries FOREIGN KEY (id) REFERENCES vault_entries (id);
ALTER TABLE external_accounts ADD CONSTRAINT fk_external_accounts_platform_id_platforms FOREIGN KEY (platform_id) REFERENCES platforms (id);
ALTER TABLE external_account_relationships ADD CONSTRAINT fk_external_account_relationships_owner_account_id_ext_d7d913bd FOREIGN KEY (owner_account_id) REFERENCES external_accounts (id);
ALTER TABLE external_account_relationships ADD CONSTRAINT fk_external_account_relationships_target_account_id_ex_0316c4ab FOREIGN KEY (target_account_id) REFERENCES external_accounts (id);
ALTER TABLE follower_snapshots ADD CONSTRAINT fk_follower_snapshots_owner_account_id_external_accounts FOREIGN KEY (owner_account_id) REFERENCES external_accounts (id);
ALTER TABLE follower_snapshot_entries ADD CONSTRAINT fk_follower_snapshot_entries_snapshot_id_follower_snapshots FOREIGN KEY (snapshot_id) REFERENCES follower_snapshots (id);
ALTER TABLE follower_snapshot_entries ADD CONSTRAINT fk_follower_snapshot_entries_target_account_id_externa_130a4317 FOREIGN KEY (target_account_id) REFERENCES external_accounts (id);
ALTER TABLE feed_items ADD CONSTRAINT fk_feed_items_feed_source_id_feed_sources FOREIGN KEY (feed_source_id) REFERENCES feed_sources (id);
ALTER TABLE saved_resources ADD CONSTRAINT fk_saved_resources_id_vault_entries FOREIGN KEY (id) REFERENCES vault_entries (id);
ALTER TABLE saved_resources ADD CONSTRAINT fk_saved_resources_feed_item_id_feed_items FOREIGN KEY (feed_item_id) REFERENCES feed_items (id);
ALTER TABLE saved_resource_conversions ADD CONSTRAINT fk_saved_resource_conversions_saved_resource_id_saved_resources FOREIGN KEY (saved_resource_id) REFERENCES saved_resources (id);
ALTER TABLE saved_resource_conversions ADD CONSTRAINT fk_saved_resource_conversions_target_vault_entry_id_va_21e9a321 FOREIGN KEY (target_vault_entry_id) REFERENCES vault_entries (id);
ALTER TABLE import_job_items ADD CONSTRAINT fk_import_job_items_import_job_id_import_jobs FOREIGN KEY (import_job_id) REFERENCES import_jobs (id);
ALTER TABLE import_job_items ADD CONSTRAINT fk_import_job_items_duplicate_vault_entry_id_vault_entries FOREIGN KEY (duplicate_vault_entry_id) REFERENCES vault_entries (id);
ALTER TABLE import_job_items ADD CONSTRAINT fk_import_job_items_imported_vault_entry_id_vault_entries FOREIGN KEY (imported_vault_entry_id) REFERENCES vault_entries (id);
ALTER TABLE wallets ADD CONSTRAINT fk_wallets_currency_code_currencies FOREIGN KEY (currency_code) REFERENCES currencies (code);
ALTER TABLE transaction_categories ADD CONSTRAINT fk_transaction_categories_parent_category_id_transacti_9eca7737 FOREIGN KEY (parent_category_id) REFERENCES transaction_categories (id);
ALTER TABLE financial_transactions ADD CONSTRAINT fk_financial_transactions_category_id_transaction_categories FOREIGN KEY (category_id) REFERENCES transaction_categories (id);
ALTER TABLE financial_transactions ADD CONSTRAINT fk_financial_transactions_generated_by_recurring_rule__578bb41e FOREIGN KEY (generated_by_recurring_rule_id) REFERENCES recurring_transaction_rules (id);
ALTER TABLE financial_transaction_entries ADD CONSTRAINT fk_financial_transaction_entries_transaction_id_financ_5c5e3a03 FOREIGN KEY (transaction_id) REFERENCES financial_transactions (id);
ALTER TABLE financial_transaction_entries ADD CONSTRAINT fk_financial_transaction_entries_wallet_id_wallets FOREIGN KEY (wallet_id) REFERENCES wallets (id);
ALTER TABLE recurring_transaction_rules ADD CONSTRAINT fk_recurring_transaction_rules_category_id_transaction_80e9df8f FOREIGN KEY (category_id) REFERENCES transaction_categories (id);
ALTER TABLE recurring_rule_weekdays ADD CONSTRAINT fk_recurring_rule_weekdays_recurring_rule_id_recurring_83481916 FOREIGN KEY (recurring_rule_id) REFERENCES recurring_transaction_rules (id);
ALTER TABLE recurring_rule_entries ADD CONSTRAINT fk_recurring_rule_entries_recurring_rule_id_recurring__3d649ec1 FOREIGN KEY (recurring_rule_id) REFERENCES recurring_transaction_rules (id);
ALTER TABLE recurring_rule_entries ADD CONSTRAINT fk_recurring_rule_entries_wallet_id_wallets FOREIGN KEY (wallet_id) REFERENCES wallets (id);
ALTER TABLE subscriptions ADD CONSTRAINT fk_subscriptions_currency_code_currencies FOREIGN KEY (currency_code) REFERENCES currencies (code);
ALTER TABLE subscriptions ADD CONSTRAINT fk_subscriptions_payment_wallet_id_wallets FOREIGN KEY (payment_wallet_id) REFERENCES wallets (id);
ALTER TABLE subscriptions ADD CONSTRAINT fk_subscriptions_recurring_rule_id_recurring_transaction_rules FOREIGN KEY (recurring_rule_id) REFERENCES recurring_transaction_rules (id);
ALTER TABLE personal_profiles ADD CONSTRAINT fk_personal_profiles_nationality_code_countries FOREIGN KEY (nationality_code) REFERENCES countries (code);
ALTER TABLE personal_profiles ADD CONSTRAINT fk_personal_profiles_address_id_addresses FOREIGN KEY (address_id) REFERENCES addresses (id);

CREATE INDEX idx_refresh_tokens_user_id ON refresh_tokens (user_id);
CREATE INDEX idx_refresh_tokens_expires_at ON refresh_tokens (expires_at);
CREATE INDEX idx_vault_entries_entry_type ON vault_entries (entry_type);
CREATE INDEX idx_vault_entries_deleted_at ON vault_entries (deleted_at);
CREATE INDEX idx_vault_entry_tags_tag_id ON vault_entry_tags (tag_id);
CREATE INDEX idx_fictions_title ON fictions (title);
CREATE INDEX idx_fictions_original_title ON fictions (original_title);
CREATE INDEX idx_fictions_genre_id ON fictions (genre_id);
CREATE INDEX idx_fiction_links_fiction_id ON fiction_links (fiction_id);
CREATE INDEX idx_films_title ON films (title);
CREATE INDEX idx_films_original_title ON films (original_title);
CREATE INDEX idx_film_genre_assignments_genre_id ON film_genre_assignments (genre_id);
CREATE INDEX idx_film_links_film_id ON film_links (film_id);
CREATE INDEX idx_film_credits_film_id ON film_credits (film_id);
CREATE INDEX idx_film_credits_person_id ON film_credits (person_id);
CREATE INDEX idx_film_credits_film_id_person_id_character_name ON film_credits (film_id, person_id, character_name);
CREATE INDEX idx_images_album_id ON images (album_id);
CREATE INDEX idx_images_captured_at ON images (captured_at);
CREATE INDEX idx_images_checksum_sha256 ON images (checksum_sha256);
CREATE INDEX idx_brands_name ON brands (name);
CREATE INDEX idx_locations_brand_id ON locations (brand_id);
CREATE INDEX idx_locations_name ON locations (name);
CREATE INDEX idx_location_category_assignments_category_id ON location_category_assignments (category_id);
CREATE UNIQUE INDEX uq_location_business_hours_location_id_day_of_week_sequence ON location_business_hours (location_id, day_of_week, sequence);
CREATE INDEX idx_study_items_title ON study_items (title);
CREATE INDEX idx_study_items_type ON study_items (type);
CREATE INDEX idx_study_items_learning_status ON study_items (learning_status);
CREATE INDEX idx_study_items_site_domain ON study_items (site_domain);
CREATE INDEX idx_study_items_youtube_channel_account_id ON study_items (youtube_channel_account_id);
CREATE INDEX idx_information_items_title ON information_items (title);
CREATE INDEX idx_information_items_type ON information_items (type);
CREATE INDEX idx_vocabulary_items_word ON vocabulary_items (word);
CREATE INDEX idx_vocabulary_items_language_code ON vocabulary_items (language_code);
CREATE INDEX idx_vocabulary_items_learning_status ON vocabulary_items (learning_status);
CREATE INDEX idx_vocabulary_items_next_review_at ON vocabulary_items (next_review_at);
CREATE INDEX idx_vocabulary_reviews_vocabulary_id ON vocabulary_reviews (vocabulary_id);
CREATE INDEX idx_vocabulary_reviews_reviewed_at ON vocabulary_reviews (reviewed_at);
CREATE INDEX idx_notes_title ON notes (title);
CREATE INDEX idx_notes_imported_file_hash ON notes (imported_file_hash);
CREATE INDEX idx_music_tracks_title ON music_tracks (title);
CREATE INDEX idx_music_tracks_platform_id ON music_tracks (platform_id);
CREATE INDEX idx_shopping_items_name ON shopping_items (name);
CREATE INDEX idx_shopping_items_status ON shopping_items (status);
CREATE INDEX idx_software_items_name ON software_items (name);
CREATE INDEX idx_software_items_type ON software_items (type);
CREATE INDEX idx_external_accounts_platform_id ON external_accounts (platform_id);
CREATE INDEX idx_external_accounts_username ON external_accounts (username);
CREATE INDEX idx_external_accounts_external_id ON external_accounts (external_id);
CREATE UNIQUE INDEX uq_external_accounts_platform_id_external_id ON external_accounts (platform_id, external_id);
CREATE UNIQUE INDEX uq_external_account_relationships_owner_account_id_tar_1a832f09 ON external_account_relationships (owner_account_id, target_account_id);
CREATE INDEX idx_external_account_relationships_follower_status ON external_account_relationships (follower_status);
CREATE INDEX idx_external_account_relationships_follow_status ON external_account_relationships (follow_status);
CREATE INDEX idx_external_account_relationships_source ON external_account_relationships (source);
CREATE INDEX idx_follower_snapshots_owner_account_id ON follower_snapshots (owner_account_id);
CREATE INDEX idx_follower_snapshots_captured_at ON follower_snapshots (captured_at);
CREATE INDEX idx_follower_snapshot_entries_target_account_id ON follower_snapshot_entries (target_account_id);
CREATE INDEX idx_feed_items_feed_source_id ON feed_items (feed_source_id);
CREATE INDEX idx_feed_items_external_id ON feed_items (external_id);
CREATE INDEX idx_feed_items_published_at ON feed_items (published_at);
CREATE UNIQUE INDEX uq_feed_items_feed_source_id_external_id ON feed_items (feed_source_id, external_id);
CREATE UNIQUE INDEX uq_feed_items_feed_source_id_url_hash ON feed_items (feed_source_id, url_hash);
CREATE INDEX idx_saved_resources_kind ON saved_resources (kind);
CREATE INDEX idx_saved_resources_title ON saved_resources (title);
CREATE INDEX idx_saved_resources_external_id ON saved_resources (external_id);
CREATE INDEX idx_import_job_items_import_job_id ON import_job_items (import_job_id);
CREATE UNIQUE INDEX uq_import_job_items_import_job_id_item_index ON import_job_items (import_job_id, item_index);
CREATE INDEX idx_wallets_active ON wallets (active);
CREATE INDEX idx_wallets_deleted_at ON wallets (deleted_at);
CREATE INDEX idx_transaction_categories_parent_category_id ON transaction_categories (parent_category_id);
CREATE INDEX idx_financial_transactions_type ON financial_transactions (type);
CREATE INDEX idx_financial_transactions_status ON financial_transactions (status);
CREATE INDEX idx_financial_transactions_occurred_at ON financial_transactions (occurred_at);
CREATE INDEX idx_financial_transactions_category_id ON financial_transactions (category_id);
CREATE INDEX idx_financial_transactions_deleted_at ON financial_transactions (deleted_at);
CREATE INDEX idx_financial_transaction_entries_transaction_id ON financial_transaction_entries (transaction_id);
CREATE INDEX idx_financial_transaction_entries_wallet_id ON financial_transaction_entries (wallet_id);
CREATE UNIQUE INDEX uq_financial_transaction_entries_transaction_id_wallet_id ON financial_transaction_entries (transaction_id, wallet_id);
CREATE INDEX idx_recurring_transaction_rules_active ON recurring_transaction_rules (active);
CREATE INDEX idx_recurring_transaction_rules_next_run_at ON recurring_transaction_rules (next_run_at);
CREATE INDEX idx_recurring_transaction_rules_deleted_at ON recurring_transaction_rules (deleted_at);
CREATE INDEX idx_recurring_rule_entries_recurring_rule_id ON recurring_rule_entries (recurring_rule_id);
CREATE INDEX idx_recurring_rule_entries_wallet_id ON recurring_rule_entries (wallet_id);
CREATE UNIQUE INDEX uq_recurring_rule_entries_recurring_rule_id_wallet_id ON recurring_rule_entries (recurring_rule_id, wallet_id);
CREATE INDEX idx_subscriptions_active ON subscriptions (active);
CREATE INDEX idx_subscriptions_next_billing_date ON subscriptions (next_billing_date);
CREATE INDEX idx_subscriptions_deleted_at ON subscriptions (deleted_at);
CREATE INDEX idx_diary_entries_entry_date ON diary_entries (entry_date);
CREATE INDEX idx_diary_entries_deleted_at ON diary_entries (deleted_at);
CREATE INDEX idx_personal_profiles_name ON personal_profiles (name);
CREATE INDEX idx_personal_profiles_relationship ON personal_profiles (relationship);
CREATE INDEX idx_personal_profiles_deleted_at ON personal_profiles (deleted_at);

-- PostgreSQL-only invariants explicitly required by the frozen v1 implementation notes.
CREATE UNIQUE INDEX uq_ci_app_users_email ON app_users (lower(email));
CREATE UNIQUE INDEX uq_ci_app_users_username ON app_users (lower(username));
CREATE UNIQUE INDEX uq_ci_tags_name ON tags (lower(name));
CREATE UNIQUE INDEX uq_ci_fiction_genres_name ON fiction_genres (lower(name));
CREATE UNIQUE INDEX uq_ci_film_genres_name ON film_genres (lower(name));
CREATE UNIQUE INDEX uq_ci_story_archetypes_name ON story_archetypes (lower(name));
CREATE UNIQUE INDEX uq_ci_world_settings_name ON world_settings (lower(name));
CREATE UNIQUE INDEX uq_ci_location_categories_name ON location_categories (lower(name));
CREATE UNIQUE INDEX uq_personal_profiles_one_active_self ON personal_profiles (is_self) WHERE is_self = true AND deleted_at IS NULL;

-- Intentionally deferred to owning module/application logic or later focused migrations:
-- subtype consistency with vault_entries.entry_type; vault capability rules; external-account
-- cross-table type/platform rules; finance transaction shape/category rules; recurring schedule
-- frequency compatibility; soft-delete dependency consistency; permanent-delete referential
-- policy; and pg_trgm/global-search indexes.
